#!/bin/sh

set -e

jsipfs init 2> /dev/null || echo "Repo already initialized. Moving on..."

if [ -n "$IPFS_API_HOST" ]; then
  sed -i "s/127.0.0.1/$IPFS_API_HOST/g" $IPFS_PATH/config
fi

exec jsipfs "$@"
